### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by tshemsedinov** [Suspensium/discord-local-music-bot#2]
- Magic numbers, like this
https://github.com/Suspensium/discord-local-music-bot/blob/f2c894c708bf773fa79f6bfc1f0049c655efe5f9/src/handlers/Client.js#L7
- Switch/case and if-else hell: like here: https://github.com/Suspensium/discord-local-music-bot/blob/f2c894c708bf773fa79f6bfc1f0049c655efe5f9/src/events/interactionCreate.js#L14
- See this lectures to fix: https://www.youtube.com/playlist?list=PLHhi8ymDMrQb3PVcPFAUI-ZgtAMkpq9yV

**Comment by tshemsedinov** [comment]
Very small and boilerplate project

**Comment by Suspensium** [comment]
Thank you, fixed issues you mentioned.
